name: OWASP Dependency Check

on:
  push:
    branches: [ main, master, 'feature/*', 'feature_*' ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 6-7'

jobs:
  owasp-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Run OWASP Dependency Check
      run: mvn org.owasp:dependency-check-maven:check
    
    - name: Archive OWASP results
      uses: actions/upload-artifact@v3
      with:
        name: owasp-dependency-check-report
        path: '**/target/dependency-check/**'
        retention-days: 90